version: '3.3'

services:
  
  postgres:
    image: "postgres"
    env_file:
      - database.env
 #   environment:
 #     POSTGRES_USER: ${POSTGRES_USER}
 #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
 #     POSTGRES_DB: ${POSTGRES_DB}
#    command: echo "host    all    all    0.0.0.0/0    md5" >> /var/lib/postgresql/data/pg_hba.conf
    volumes:
     - pgdata:/var/libpostgresql/data/
     
  test_postgres:
    image: "postgres"
    container_name: test_database
    env_file:
      - test_database.env
  #  environment:
  #    POSTGRES_USER: ${POSTGRES_TEST_DB_USER}
  #    POSTGRES_PASSWORD: ${POSTGRES_TEST_DB_PASSWORD}
  #    POSTGRES_DB: ${POSTGRES_TEST_DB}
    expose:
     - "5433"
    ports:
     - "5433:5433"
    command: -p 5433 
     
  flask:
    build: ./
    container_name: hopnets_app
    restart: always
    command: tail -F anything
    ports:
      - "5000:5000"
    volumes:
      - ./flask-image/:/usr/src/app:rw

volumes:
  pgdata: {}