version: '3.3'

services:
  
  postgres:
    image: "postgres"
    env_file:
     - database.env
#    command: echo "host    all    all    0.0.0.0/0    md5" >> /var/lib/postgresql/data/pg_hba.conf
    volumes:
     - pgdata:/var/libpostgresql/data/

  flask:
    build: ./
    container_name: hopnets_app
    restart: always
    command: tail -F anything
    ports:
      - "5000:5000"
    volumes:
      - ./flask-image/:/usr/src/app:rw

volumes:
  pgdata: {}