"""empty message

Revision ID: 460362b67439
Revises: 83a12164c4fd
Create Date: 2022-03-18 13:27:29.003637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460362b67439'
down_revision = '83a12164c4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quotation_name_key', 'quotation', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('quotation_name_key', 'quotation', ['name'])
    # ### end Alembic commands ###
