"""empty message

Revision ID: 534495b0cf97
Revises: a451816b629f
Create Date: 2021-11-11 11:46:07.411940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534495b0cf97'
down_revision = 'a451816b629f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tag', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    # ### end Alembic commands ###
