"""empty message

Revision ID: 77540700704d
Revises: cd934311f8d1
Create Date: 2021-04-29 19:52:18.362994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77540700704d'
down_revision = 'cd934311f8d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
