"""empty message

Revision ID: 9ae41e2b6961
Revises: 389cf9962331
Create Date: 2022-03-28 13:25:10.618496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae41e2b6961'
down_revision = '389cf9962331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'net_table', ['provider_id', 'quotation_id', 'order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'net_table', type_='unique')
    # ### end Alembic commands ###
