"""empty message

Revision ID: a21bb7d39dd4
Revises: 5f5be8f142f0
Create Date: 2022-03-28 13:11:37.137371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21bb7d39dd4'
down_revision = '5f5be8f142f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_table',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_pricing.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('provider_id', 'quotation_id', 'order_id'),
    sa.UniqueConstraint('provider_id', 'quotation_id', 'order_id')
    )
    op.drop_constraint('provider_pricing_quotation_id_fkey', 'provider_pricing', type_='foreignkey')
    op.drop_constraint('provider_pricing_order_id_fkey', 'provider_pricing', type_='foreignkey')
    op.drop_column('provider_pricing', 'order_id')
    op.drop_column('provider_pricing', 'quotation_id')
    op.drop_column('provider_pricing', 'net')
    op.add_column('quotation', sa.Column('net', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation', 'net')
    op.add_column('provider_pricing', sa.Column('net', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('provider_pricing', sa.Column('quotation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('provider_pricing', sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('provider_pricing_order_id_fkey', 'provider_pricing', 'order', ['order_id'], ['id'])
    op.create_foreign_key('provider_pricing_quotation_id_fkey', 'provider_pricing', 'quotation', ['quotation_id'], ['id'])
    op.drop_table('net_table')
    # ### end Alembic commands ###
