"""empty message

Revision ID: cd934311f8d1
Revises: 81681f4d19d9
Create Date: 2021-04-09 13:27:07.446492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd934311f8d1'
down_revision = '81681f4d19d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'feature_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'feature_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
