"""empty message

Revision ID: fd7083e7e777
Revises: 75b987525552
Create Date: 2022-03-29 09:07:21.170975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7083e7e777'
down_revision = '75b987525552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_ref_associations',
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_table.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_pricing.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('provider_id', 'quotation_id', 'order_id')
    )
    op.drop_table('net_ref')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('net_ref',
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quotation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order_table.id'], name='net_ref_order_id_fkey'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_pricing.id'], name='net_ref_provider_id_fkey'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], name='net_ref_quotation_id_fkey'),
    sa.PrimaryKeyConstraint('provider_id', 'quotation_id', 'order_id', name='net_ref_pkey')
    )
    op.drop_table('network_ref_associations')
    # ### end Alembic commands ###
